# Generated by Django 6.0.6 on 2026-06-19 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_profesional_usuario_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'RESERVADO')), fields=('profesional', 'fecha', 'hora'), name='turno_reservado_unico'),
        ),
    ]
